# Generated by Django 5.2 on 2025-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_user_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('professional', 'Profesional Independiente'), ('consultant_company', 'Empresa Consultora'), ('direct_company', 'Empresa Directa')], max_length=20),
        ),
    ]
